Updated the documentation of the API endpoints and there description
skunkforce/omnai_analysis-api-documentation_ref pull request #1
Opened 2024-09-03 14:18 UTC by AKMaily

2024-09-03 16:28 UTC, dobe-1 requested changes

2024-09-03 16:28 UTC, dobe-1 commented on openapi.json
> +          "meta": {
I think it is not necessary to define a `meta` object here. The description and the properties can be defined directly in the `result` object. If you have a different opinion please correct me.

2024-09-03 16:28 UTC, dobe-1 commented on openapi.json
> +            "title": "Daten",
This line can be removed

2024-09-04 06:13 UTC, AKMaily commented on openapi.json
> +          "meta": {
So the correct order would be 
Result: { 
    type: object ,  
   description, 
    properties: { }}} ?

2024-09-16 10:05 UTC, dobe-1 commented on openapi.json
> +          "meta": {
Yes

2024-10-29 07:44 UTC, merged